version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: carpark-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: carpark-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/backend
    volumes:
      - ./backend:/app
    restart: unless-stopped

  db:
    image: mariadb:11
    container_name: carpark-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carpark-phpmyadmin
    depends_on:
      - db
    ports:
      - "5480:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    restart: unless-stopped

volumes:
  mariadb_data:
